### ISSUE TITLE
Add a .ruby-version

### ISSUE THREAD

**Issue by justinkim** [Team694/teammanager#19]
Contents should be:

```
1.9.3
```

or whatever ruby version teammanager requires. I think it's 1.9.3, based on age and a quick look at the Gemfile.lock.

**Comment by kevinwang** [comment]
The last deploy still built with 1.9.2, with this in the build log:

```
###### WARNING:
       You have not declared a Ruby version in your Gemfile.
       To set your Ruby version add this line to your Gemfile:
       ruby '1.9.2'
       # See https://devcenter.heroku.com/articles/ruby-versions for more information.
```

**Comment by ivywong** [comment]
So do I add that to the Gemfile...? Because Justin has a separate branch for 1.9.3 stuff.

**Comment by justinkim** [comment]
Yes, because Heroku is our deployment platform. I've never seen declaring the ruby version in the Gemfile, but if Heroku wants it, then we should have it there.
